### ISSUE TITLE
Trying to run an older project but docker-php-ext-enable phalcon is not recognised

### ISSUE THREAD

**Issue by spoilerdo** [phalcon/invo#100]
When I am trying to run my project with the provided dockerfile in this git and changing the Phalcon version to 3.1.1 and PHP version to 7.4 I get the following on the step:
```
RUN docker-php-ext-enable \
    opcache \
    phalcon \
    xdebug
```
phalcon does not exist. I cannot check it on a newer version because it is an old project.

**Comment by niden** [comment]
If you notice the dockerfile it installs phalcon from PECL and the line you posted enables the module.

Phalcon v3 does not exist in PECL so the line fails undersandably. You will need to remove phalcon from this line (shown above) and the one that installs it through PECL, then clone the repository, checkout the tag of the version you want, compile it and then enable the module in your environment via the necessary ini directive

**Comment by spoilerdo** [comment]
I just fixed it by migrating the entire project to a higher version. A project should not be running in v3.
