### ISSUE TITLE
Is DB_HOST=localhost correct?

### ISSUE THREAD

**Issue by s-ohnishi** [phalcon/invo#101]
I'm having trouble running migrations.
(I'm trying with the latest v2.0.0)

when I run
```
vendor/bin/phalcon-migrations list --config=migrations.php
```
becomes this.
```
Fatal Error: SQLSTATE[HY000] [2002] No such file or directory
```

The file `.env.example` says `DB_HOST=localhost` and `docker-compose.yml` looks like this.
  ```
   mysql:
     container_name: invo-mysql
     hostname: invo-mysql
```

Thinking that this is an error that occurs because the host name is different like this, I rewrote `.env` to `DB_HOST=invo-mysql` and executed
```
Phalcon Migrations

┌──────────────────┬───────────────┐
│ Version          │ Was applied   │
├──────────────────┼───────────────┤
│ 1.0.0            │ N             │
└──────────────────┴───────────────┘
```
It will be displayed.

Again, I think `DB_HOST=localhost` in `.env` is incorrect.
Does it have to be `localhost` for automatic execution of .github/workflows/main.yml?

**Comment by niden** [comment]
I added a clarification in the `.env.example` file.

Thank you @s-ohnishi 

https://github.com/phalcon/invo/commit/59acba7f5da74696a7a74d47a02708cbe306629b
