### ISSUE TITLE
Fatal error: Phalcon\Acl\Adapter\Memory::isAllowed()

### ISSUE THREAD

**Issue by doit76** [phalcon/invo#18]
Fatal error: Phalcon\Acl\Adapter\Memory::isAllowed(): The argument is not iterable() in /storage/htdocs/sites/invo/app/plugins/Security.php on line 92

**Comment by sergeysviridenko** [comment]
I couldn't reproduce this issue. It works fine for me. I propose close this issue. If it appears again, we'll open new one.
