### ISSUE TITLE
Should the DB instance be shared

### ISSUE THREAD

**Issue by aleemb** [phalcon/invo#19]
Shouldn't the DB instance in `index.php` dependency injector be a shared instance? I noticed in my own testing that it drastically reduces the number of connections per request.

**Comment by chiWahWong** [comment]
Thanks for your question @aleemb. It also makes me think about should the rest be shared. I found something: http://stackoverflow.com/questions/21900336/all-requests-requiring-connection-to-mysql-are-very-very-slow-using-phalcon and seem like it may be better to set it as shared.

**Comment by aleemb** [comment]
There is no additional cost. It reduces the memory footprint since you have a single shared db instance versus having many instances. There is no point creating 10 instances when you can piggyback on a single instance.

The performance degrades with non-shared instances because not only is a new instance created but a new connection as well.

In summary, there is no reason for it not to be shared.

**Comment by chiWahWong** [comment]
@aleemb I've found a blog article 
http://jmprog.blogspot.com/2010/01/costs-and-benefits-of-singleton-pattern.html
and a stackoverflow discussion:
http://stackoverflow.com/questions/137975/what-is-so-bad-about-singletons
both indicating that it may be a problem for the memory; and there are quite some readings I found that's helpful to understand the topic.

**Comment by aleemb** [comment]
What does singletons have to do with it?

**Comment by chiWahWong** [comment]
http://docs.phalconphp.com/en/latest/reference/di.html#shared-services

**Comment by aleemb** [comment]
> I have a doubt, could registering services as "shared" cost more memory?

A single instance uses less memory than multiple instances

> http://docs.phalconphp.com/en/latest/reference/di.html#shared-services

Phalcon uses a service locator not a singleton https://www.google.com/#q=service%20locator%20singleton

**Comment by chiWahWong** [comment]
"Services can be registered as “shared” services this means that they always will act as singletons." - Phalcon doc

**Comment by chiWahWong** [comment]
older Phalcon blog http://blog.phalconphp.com/post/36213237029/phalcon-0-7-0-beta-released

**Comment by aleemb** [comment]
As I said, this is a service locator and not a classical singleton pattern. Required reading:

* misko.hevery.com/2008/08/17/singletons-are-pathological-liars/
* http://stackoverflow.com/questions/6034748/if-singletons-are-bad-then-why-is-a-service-container-good

**Comment by chiWahWong** [comment]
The doc explicitly said it is.

**Comment by sergeyklay** [comment]
Fixed in the `0.6.x` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.
