### ISSUE TITLE
Phalcon/INVO not too fond of tilde (~) characters in config.ini

### ISSUE THREAD

**Issue by DarkerGlobe** [phalcon/invo#25]
Hi Phalcon Devs,

I use CPanel and its password generator uses several special characters for security, including the ~ character. Unfortunately placing that password into the config file for INVO will cause the config.ini parser to fail.

I got round the issue by moving the database config from config.ini into the bootstrap so it's not a high priority but it would probably be better if the parser could handle it rather than die.

Many thanks for your hard work.

**Comment by sergeysviridenko** [comment]
I couldn't reproduce this issue. I've used password `s~1`.
I propose to close this issue.
