### ISSUE TITLE
ProductsForm - Numericality Not Found

### ISSUE THREAD

**Issue by mabon** [phalcon/invo#30]
Fatal error: Class 'Phalcon\Validation\Validator\Numericality' not found in /.../invo/app/forms/ProductsForm.php on line 52

Changed line 9 from:

use Phalcon\Validation\Validator\Numericality; 

to:

use Phalcon\Mvc\Model\Validator\Numericality;

**Comment by sergeysviridenko** [comment]
I couldn't reproduce this issue. it works fine for me. class `Phalcon\Validation\Validator\Numericality` is exist. I propose to close this issue.
