### ISSUE TITLE
Phalcon invo - volt does not compile

### ISSUE THREAD

**Issue by saadjabrane** [phalcon/invo#31]
New to phalcon, installed phalcon on mac followed instruction, got invo. when loading localhost/invo got Error code: ERR_EMPTY_RESPONSE on chrome. No cache volt.php in invo/cache/volt have already chmod 777 -R invo so it's not access right. 
Debugged under phpstorm failure (Process finished with exit code 139) in services.php
line 80     $compiler->addFunction('is_a', 'is_a');

Anyone can help ?

**Comment by sergeysviridenko** [comment]
@saadjabrane on ubuntu it works very well. Was this problem solved?

**Comment by sergeysviridenko** [comment]
I propose to close this issue. There isn't any reaction.
