### ISSUE TITLE
Register new User

### ISSUE THREAD

**Issue by harksin** [phalcon/invo#33]
hello actualy register new user don't work

<code>  $request->getPost  </code>
need to be change in
<code> $this->request->getPos  </code>

my instlation of falcon can create this Bug?
if you have similar bug i can commit It.

regards, 

Harksin

All:
<code>  $name = $this->request->getPost('name', array('string', 'striptags'));
$username = $this->request->getPost('username', 'alphanum');
$email = $this->request->getPost('email', 'email');
$password = $this->request->getPost('password');
$repeatPassword = $this->request->getPost('repeatPassword');</code>

**Comment by sergeysviridenko** [comment]
This bug was fixed by `zhangyiluo`. Creating new users work fine. I propose close this issue.
