### ISSUE TITLE
Script 'createdb.php' and 'password' field length on 'users' table

### ISSUE THREAD

**Issue by kaiohken1982** [phalcon/invo#35]
The script createdb.php will create the password field of 30 char length but SHA1 hash algorithm, that is used for login, is of 40 char length, so in order to login the user.password field must be altered to length of 40. 
Someone else has encountered this problem?

**Comment by sergeysviridenko** [comment]
This problem was solved. Now `password` creates with 40 char length. I propose to close this issue.
