### ISSUE TITLE
ProductsController.php is not working, bad line in ProductsForm.php

### ISSUE THREAD

**Issue by CarbonMDM** [phalcon/invo#39]
You have a bad code in line 121, $form->isValid($data, $product)
This line causes error 'Internal Error
Something went wrong, if the error continue please contact us'

Even if u disable form validation (from line 121 to line 126 this script is NOT working - does nothing (does not update products even it if say 'Product was updated successfully'.).

Probably same with '!$form->isValid($data, $product)' in line 85 - does not create new product. same error.

There is as well error in line 9 of ProductsForm.php.
Instead 'use Phalcon\Validation\Validator\Numericality;' should be 
'use Phalcon\Mvc\Model\Validator\Numericality;'

Anyay the question is how the correct path should look like for all classes (if in this example app this is bad)?

Tested on xampp with phalcon version 1.3.4

**Comment by sergeysviridenko** [comment]
Now there are all fine in this file. There isn't line 121 and any validation. I propose to close this issue.
