### ISSUE TITLE
SecurityPlugin.php Access Control List logic bug

### ISSUE THREAD

**Issue by tonywonghk** [phalcon/invo#40]
![screen shot 2014-12-21 at 11 33 57 pm](https://cloud.githubusercontent.com/assets/2988894/5518590/e32ce84c-8969-11e4-959f-29bd5d1c5bd1.png)

this line using '*' as action value would be introduced access control fail. resulting inconsistent access change result in line 110 "$allowed = $acl->isAllowed($role, $controller, $action);"

the code should be changed to as attached.
![screen shot 2014-12-21 at 11 37 15 pm](https://cloud.githubusercontent.com/assets/2988894/5518601/5690bc3c-896a-11e4-9c57-c21f0ac5ac26.png)

**Comment by sergeysviridenko** [comment]
This code was implemented. I propose close this issue.
