### ISSUE TITLE
minor mistakes

### ISSUE THREAD

**Issue by chiWahWong** [phalcon/invo#42]
app\plugins\NotFoundPlugin:

"This action is executed before execute any action in the application" may have to change to a more accurate description.

---

app\config\services.php:

"a user component"

---

app\config\services.php:

"If the configuration specify the use of metadata adapter use it or use memory otherwise" may have to change to a more accurate description.

---

app\controllers\RegisterController.php:

"diferent"

---

app/views/register/index.volt:

is the "input-xlarge" no longer being used? Further more seem like the "repeatPassword" need "form-control".

---

app/views/errors/show404.volt:

"accesed"

---

app\plugins\SecurityPlugin:

"session" do not have "registerAction" anymore

**Comment by sergeyklay** [comment]
Fixed in the `0.6.x` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.
