### ISSUE TITLE
V4 Upgrade

### ISSUE THREAD

**Issue by ruudboon** [phalcon/invo#76]
We would like to keep supporting Invo in v4. Invo is a great starting point for our users that are learning Phalcon.
* [x] Create new v4 upgrade branch for pulls
* [x] Make Invo v4 compatible
* [ ] ~Upgrade documentation~ (https://github.com/phalcon/docs/issues/2630)

**Comment by Jeckerson** [comment]
Moved 3d action point into separate issue in docs repository - https://github.com/phalcon/docs/issues/2630
