### ISSUE TITLE
unit testing examples?

### ISSUE THREAD

**Issue by jellisii** [phalcon/invo#79]
Is there a way a complete coverage unit tests could be written for the app?  I struggle with how to build out testing for my own apps, and a good example would be well appreciated.

**Comment by sergeyklay** [comment]
Right now we can offer https://github.com/Codeception/phalcon-demo for Phalcon v3.x

**Comment by Jeckerson** [comment]
Also, you can check Vokuro tests in `4.0.x` branch, might help - https://github.com/phalcon/vokuro/tree/4.0.x/tests

**Comment by Jeckerson** [comment]
Done.
