### ISSUE TITLE
Dotenv is necessary?

### ISSUE THREAD

**Issue by s-ohnishi** [phalcon/invo#98]
config/config.php is rewritten from
```
    'database' => [
        'adapter' => getenv('DB_ADAPTER'),
        'host' => getenv('DB_HOST'),
        'username' => getenv('DB_USERNAME'),
        'password' => getenv('DB_PASSWORD'),
        'dbname' => getenv('DB_DBNAME'),
        'charset' => getenv('DB_CHARSET'),
],
```
to
```
    'database' => [
        'adapter'  => $_ENV['DB_ADAPTER'] ?? 'Mysql',
        'host'     => $_ENV['DB_HOST'] ?? 'locahost',
        'username' => $_ENV['DB_USERNAME'] ?? 'phalcon',
        'password' => $_ENV['DB_PASSWORD'] ?? 'secret',
        'dbname'   => $_ENV['DB_DBNAME'] ?? 'phalcon_invo',
        'charset'  => $_ENV['DB_CHARSET'] ?? 'utf8',
    ],
```
but after the change, $_ENV is referenced and Dotenv is not used, so isn't Dotenv unnecessary?

Also, in .env.example, `DB_DBNAME=invo`, but the database name is changed like ` 'dbname' => $_ENV['DB_DBNAME'] ?? 'phalcon_invo',` Is it intentional?

**Comment by niden** [comment]
`DotEnv` puts those values in `$_ENV` so that part is good. The db name needs to be fixed for consistency.

**Comment by s-ohnishi** [comment]
Thank you for your reply.

I was a little confused, but the question still persists.
As you say, if `.env` exists (if it doesn't, an exception is thrown) `DotEnv` will add the environment variables described in `.env` to $_ENV.
So $_ENV is always set to the value we need, so the value after ?? will never be used, right?

I think that the value after ?? is used only when `DotEnv` is not working.
Unless you set a value not described in `.env` in config.php, both are the same value.

**Comment by niden** [comment]
It is a safeguard in case the value in `.env` is `null` nothing more. If `.env` does not exist, you are correct, the application will complain with an exception. If for some reason those variables in `.env` are set to empty/null, then that piece of code will keep a default variable in. A bit of an overkill but we thought we'd keep it there.

**Comment by s-ohnishi** [comment]
I was convinced.
Thank you very much.

Please excuse me for one more question.
Is it okay to modify a sample application like Invo to only support v5?
for example...
I think the controller's tag property has changed from Phalcon\Tag to Phalcon\Html\TagFactory and TagFactory does not support setDefault().
To achieve the same thing, I think that Froms must be used, but it will be a major overhaul rather than a refurbishment.

**Comment by niden** [comment]
Resolved in #99

**Comment by niden** [comment]
> I was convinced. Thank you very much.
> 
> Please excuse me for one more question. Is it okay to modify a sample application like Invo to only support v5? for example... I think the controller's tag property has changed from Phalcon\Tag to Phalcon\Html\TagFactory and TagFactory does not support setDefault(). To achieve the same thing, I think that Foms must be used, but it will be a major overhaul rather than a refurbishment.

You can change the application as much or as little as you want. It is up to you, we offer it as a sample.

To be honest `setDefault()` was not a great implementation because it allowed developers to set data on the global space and that leads to bugs and potential leaks of content/data from one component to another.

To use the new `TagFactory` all you will have to do is set the `value` of each component. Yes it will be a bit tedious to do because you now have to set it up on each control but it can be done with a value array that can be used for this.

Either that or go down the Forms route as you mentioned which is indeed a bit of an overhaul.

**Comment by s-ohnishi** [comment]
> Yes it will be a bit tedious to do because you now have to set it up on each control but it can be done with a value array that can be used for this.

My knowledge of `TagFactory` is still insufficient, so I can't understand what you're saying, but I'd like to read the .zep sources and the phalcon/docs documentation and write it little by little.
I'd like to make a suggestion once the sample is working.
